name: report_issue

on:
  issues:
    types:
      - opened

jobs:
  issue_published:
    name: Issue published
    if: ${{ github.event.issues }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "A issue has been published"
